Blurred user background in app drawer
ubports/unity8 pull request #129
Opened 2019-04-19 05:45 UTC by ChristianPauly

A simple eyecandy workaround for the not working blur effect. See here in action: https://janian.de/index.php/s/jqoS9XsdRA2XbY3

![screenshot20190418_222017314](https://user-images.githubusercontent.com/24619905/56408939-079ef900-6277-11e9-87eb-cc70459963d3.png)

Unfortenetely I don't have the hardware to test this on different sizes...

2019-04-19 09:16 UTC, ChristianPauly commented
CI build failed. Looks like the same error like in #127

2019-04-19 14:21 UTC, mariogrip commented
Oh! I really like this! :D Will take a look at the ci

2019-04-19 16:14 UTC, mariogrip commented
Ok, issue should be fixed now. fixed by: https://github.com/ubports/build-tools/commit/105a02ccc8bfcd60d4b8995bebee58a3f3a8dfd1 

I have triggered a rebuild

2019-04-19 16:27 UTC, ChristianPauly commented
CI still doesn't like me:

```
The following tests FAILED:

	 16 - Whitespace (Failed)

Errors while running CTest

Makefile:130: recipe for target 'test' failed

make[1]: *** [test] Error 8

make[1]: Leaving directory '/build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpbdsc/obj-x86_64-linux-gnu'

dh_auto_test: make -j12 test ARGS+=-j12 returned exit code 2

debian/rules:12: recipe for target 'build-arch' failed

make: *** [build-arch] Error 2

dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2

I: copying local configuration

E: Failed autobuilding of package

I: user script /var/cache/pbuilder/build/cow.1356/tmp/hooks/C10shell starting

  ┌──────────────────────────────────────────────────────────────────────────────┐

  │  FTBFS - problem with building Debian package                                │

  └──────────────────────────────────────────────────────────────────────────────┘

  ┌──────────────────────────────────────────────────────────────────────────────┐

  │  DEB_KEEP_BUILD_ENV is not set to 'true', not keeping build environment      │

  └──────────────────────────────────────────────────────────────────────────────┘

```

2019-04-19 16:30 UTC, UniversalSuperBox commented
That's a genuine error in your changes.

```
/build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpbdsc/qml/Launcher/Drawer.qml: bad whitespace in line 77
```

2019-04-19 20:56 UTC, mariogrip commented
I changed the base since sorting got merged into edge :)

2019-04-19 20:58 UTC, mariogrip commented
But i do wonder, should we make this an setting set option? same as we did for dash background.

2019-04-19 21:07 UTC, ChristianPauly commented
> That's a genuine error in your changes.
> 
> ```
> /build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpbdsc/qml/Launcher/Drawer.qml: bad whitespace in line 77
> ```

I'm sorry for this 😟. I should make indentations visible in Atom...

2019-04-20 14:06 UTC, dobey commented
> But i do wonder, should we make this an setting set option? same as we did for dash background.

No we shouldn't. :)

2019-05-14 17:31 UTC, ChristianPauly commented
Hi, are there any news about this? Are there new design decisions where I can help to implement maybe?

2019-05-16 13:42 UTC, dobey commented
How does this look in landscape (on a tablet for example), or in windowed mode on an external screen?

2019-05-17 08:08 UTC, ChristianPauly commented
> How does this look in landscape (on a tablet for example), or in windowed mode on an external screen?

I will try to test this later today :)

2019-05-17 09:40 UTC, ChristianPauly commented
Okay I was able to test it with my nexus 5 in convergence mode on a full hd display:
![screenshot20190517_113535025](https://user-images.githubusercontent.com/24619905/57919140-7ed8a480-7898-11e9-95b1-b9547aef93ae.png)
![screenshot20190517_113659229](https://user-images.githubusercontent.com/24619905/57919147-80a26800-7898-11e9-95bb-e727a0a7fab8.png)

2019-05-17 12:16 UTC, NeoTheThird commented
It feels very natural on the M10, great work!

2019-05-19 08:47 UTC, kugiigi commented
Looks great on Nexus 7.
Not sure though if making the source image "visible" to false would make sense for the performance.

![screenshot20190519_164149660](https://user-images.githubusercontent.com/29456786/57979848-cd408d00-79d7-11e9-9f3b-3e46a82698a3.png)
![screenshot20190519_164131680](https://user-images.githubusercontent.com/29456786/57979849-cdd92380-79d7-11e9-9a88-7011d1749ff7.png)

2019-05-19 22:54 UTC, dobey commented
Hrmm. It looks like the wallpaper is not properly aligned in the blur versus the actual wallpaper, which makes things look a bit off, in this case. :-/

2019-05-20 09:46 UTC, NeoTheThird commented
It needs an offset of the width of the launcher

2019-05-25 15:41 UTC, kugiigi commented
To me, it's not really necessary to make it exactly aligned to the wallpaper. The goal is to make the drawer look better and not actually fool people into thinking there's real blurring. It doesn't look too off to me and people will be opening the drawer on top of apps most of the time anyway.

2019-05-26 14:42 UTC, dobey commented
> To me, it's not really necessary to make it exactly aligned to the wallpaper. The goal is to make the drawer look better and not actually fool people into thinking there's real blurring. It doesn't look too off to me and people will be opening the drawer on top of apps most of the time anyway.

But it's also a simple fix, and while it might be fine to ignore for a lot of backgrounds, it's still wrong and creates cognitive work for those who notice that something is not quite right, when trying to use the system. It needs to be aligned properly.

2019-05-26 14:44 UTC, dobey requested changes
Please fix the alignment issue of the blurred image versus the real background.

2019-05-26 16:33 UTC, ChristianPauly commented
> Please fix the alignment issue of the blurred image versus the real background.

I will try this in the next days

2019-05-29 15:33 UTC, ChristianPauly commented
I have tried it today but I wasn't able to fix this. Don't know how to align an image perfectly to a size, which is not the parent element... Also it seems like that the background of the lock screen and the real desktop background aren't aligned too.

2019-05-30 14:07 UTC, NeoTheThird commented
I don't know if the alignment should hold us up right now while there are way bigger problems still. It's not that blatantly annoying with the blur, so i'd suggest filing a bug that someone can look at it someday, but not waste too much time on it now.

2019-05-31 13:30 UTC, dobey commented
So, I haven't managed to get horizontal alignment resolved, but I did manage to fix it vertically on my nexus 5. Though it seems the lock screen has a similar alignment issue.

2019-05-31 13:30 UTC, dobey approved these changes

2019-05-31 13:31 UTC, merged

2019-06-04 11:13 UTC, dark-eye commented
Maybe [this](https://gitlab.com/dark-eye/camera-app/blob/issue_125/OverlayBlur.qml)  can help i made it to the camera-app