[TLWM] Change rootFocus to a property
ubports/unity8 pull request #229
Opened 2019-12-02 16:52 UTC by mariogrip

This changes rootFocus to a qt property insted of a callable function

2019-12-03 01:03 UTC, UniversalSuperBox requested changes
Whilte Qt *is* magic, I think you missed a step here.

2019-12-03 01:03 UTC, UniversalSuperBox commented on plugins/WindowManager/TopLevelWindowModel.h
> +    void rootFocusChanged();
This signal is never emitted

2019-12-03 01:04 UTC, mariogrip commented on plugins/WindowManager/TopLevelWindowModel.h
> +    void rootFocusChanged();
whops, will add that :D

2019-12-06 03:18 UTC, mariogrip reviewed
LGTM :+1:

2019-12-11 14:56 UTC, UniversalSuperBox approved these changes

2019-12-11 14:56 UTC, merged