Focus the shellView after creating secondaryWindow
ubports/unity8 pull request #307
Opened 2020-04-20 01:02 UTC by UniversalSuperBox

Prior to this change, 'SecondaryWindow' was the focused window after
onScreenAdded finished. By moving m_shellView->requestActivate to the
end of the method, we ensure that the real shell is focused.

Fixes https://github.com/ubports/keyboard-component/issues/123

2020-04-20 09:43 UTC, peat-psuwit requested changes

2020-04-20 09:43 UTC, peat-psuwit commented on src/ShellApplication.cpp
> +    qDebug() << "onScreenAdded()" << screens().count();
Please remove debug output.

2020-04-20 09:43 UTC, peat-psuwit commented on src/ShellApplication.cpp
> +        qDebug() << allScreens;
Please remove debug output.

2020-04-20 09:43 UTC, peat-psuwit commented on src/ShellApplication.cpp
> +        // its backing QPlatformWindow recreated). So lets refocus it.
It might be better to also mention ordering in the comment.

2020-04-21 19:08 UTC, mariogrip approved these changes
LGTM :+1:

2020-04-21 19:14 UTC, peat-psuwit approved these changes
Oh, I forgot that I explicitly requested changes and has to explicitly approve it. Sorry about that, get carried away with something else.

So it's LGTM now. With @mariogrip's approval, I'll merge it.

2020-04-21 19:15 UTC, merged