fix for notification led
ubports/unity8 pull request #359
Opened 2021-01-23 16:09 UTC by wdehoog

It seems due to the Qt 5.12 update the binding on hasMessages stopped working (why?).

The binding on icons seems to work fine so let's use that. See https://github.com/ubports/ubuntu-touch/issues/1651.

No idea how this could pass the tests but fail on the device.

Also no idea if these changes pass the tests. Lets see...

2021-01-24 19:21 UTC, dobey requested changes
While this might work around the issue, an even simpler workaround is to simply remove `valid` from the `hasMessages` check above. It seems there is where the problem actually lies, and it is not being modified properly from the C++ for some reason.

2021-01-24 19:37 UTC, wdehoog commented
To me the ``valid`` property seems needed. If I am correct it is determined here: https://github.com/ubports/unity8/blob/ac69b162683ecd80d4bcfe877d4444797f1f6930/plugins/Unity/Indicators/actionrootstate.cpp#L77

Since the icon names are checked I think it is also better to use the onIconsChanged event.

2021-01-24 20:55 UTC, dobey commented
> To me the `valid` property seems needed.

Then I guess we should figure out why `validChanged()` is not being called, and fix that, no? This is the reason that `hasMessages` isn't changed either. For some reason `validChanged` is not being emitted, thus Qt doesn't reevaluate the `hasMessages` binding to it.

2021-01-24 21:57 UTC, wdehoog commented
Even if ``validChanged`` is not fired (which indeed isn't) it's value can still be checked.

Removing ``valid`` does indeed make it work. Putting ``valid`` at the end of the expression also makes it work.
How can this happen?

2021-01-25 14:51 UTC, dobey commented
> How can this happen?

I'm not sure. Maybe there is an issue in newer Qt where it only binds the first property in such compound statements, thus when reversing them here, it evaluates a binding to `icons` which is having the `iconsChanged` emitted properly, thus causing the whole statement to be evaluated again. But using `onValidChanged` also doesn't work, since it is not being emitted (and perhaps never was being emitted before either).

2021-01-25 16:52 UTC, wdehoog commented
So what now? Is it ok like this or do you still want ``valid`` to be removed from the expression? Investigating what is going wrong under the Qt hood is out of my league.

2021-01-26 19:45 UTC, dobey approved these changes
Still not sure what exactly is causing the issue, but this seems to resolve it, so let's merge it for now. Really, notifications in UT needs a complete overhaul and most of this logic should be moved into a backend, rather than being part of the shell.

2021-01-26 19:47 UTC, merged