Re-enable disabled code for 5.9 transition
ubports/unity8 pull request #40
Opened 2018-06-02 03:48 UTC by UniversalSuperBox

This fixes https://github.com/ubports/ubuntu-touch/issues/624 by correctly overriding QQuickGeometryChange. It also fixes the tests that were disabled when upgrading to 5.9.

I abused CI with this one, please squash and merge

2018-06-02 05:14 UTC, dpniel requested changes
Awesome! Just one change needed in the tests as far as I can see.

2018-06-02 05:14 UTC, dpniel commented on tests/plugins/Ubuntu/Gestures/GestureTest.cpp
> -    windowPrivate->flushDelayedTouchEvent();
These changes might bring in a race condition where not all events have been delivered before the next comparison which assumes they have.

Looks like the api has changed, but [`flushFrameSynchronousEvents`](https://code.woboq.org/qt5/qtdeclarative/src/quick/items/qquickwindow.cpp.html#_ZN19QQuickWindowPrivate27flushFrameSynchronousEventsEv) should do the same thing and ensure all events have been delivered.

2018-06-02 14:39 UTC, UniversalSuperBox commented
I'm not sure how the remote got work I didn't have in that one, but okay.

All instances of that flush should be fixed now.

2018-06-02 18:47 UTC, dpniel approved these changes
LGTM. :+1:

2018-06-03 00:20 UTC, mariogrip approved these changes
LGTM :+1:

2018-06-03 00:20 UTC, merged