Test and use hfd if Android SDK indicates it
ubports/unity8 pull request #414
Opened 2021-10-02 18:51 UTC by Flohack74

To get LEDs working again after H9 and most newer devices requiring that API. See also https://gitlab.com/ubports/community-ports/android10/project-management/-/issues/6

2021-10-05 15:13 UTC, peat-psuwit commented
I don't particularly like tack-on override like this. At first, I would asked you to add another class implementing the same interface, and do detection at QML singleton providing time.

Although, there already exists the Hfd implementation in Unity8:
https://github.com/ubports/unity8/commit/e236c3f810c844bbe096c24eb8abb22bf595e646

It completely replaces the old backend with Hfd, using Hfd's QML plugin. Alternatively, one could use Hfd's QML plugin in addition to the current plugin. Although, note that Hfd is suppose to work on older devices too, so we might as well consider doing the transition to Hfd now...

@mariogrip, what do you think? What's the current state of Hfd?

2021-10-05 17:16 UTC, Flohack74 commented
@peat-psuwit we have LED regression now ongoing since months if not already for a whole year. I agree that this solution is not optimal, but at least it brings back functionality that is missing from the product.
The other PR looks nice, but will it work on old devices? Do we have again something thats on a branch and needs to be separately installed for >= H9 and Pinephone?
The magic about continous integration of an ever-changing feature world is to make small, sometimes silly changes that might need refactor later - which can be expensive, but with the beauty of keeping users enabled and functions functioning.
I find it really a poor approach that hfd was dropped in, stayed unfinished and the consumers around were partly adjusted to it. In the end Halium 9 was regressing from the state in H7.1 and 5.1 in at least vibrator and LEDs API a lot, and I dont think we are serving the users by keeping the fucntionality broken until we find the perfect long-term solution.
Software development in 2021 is no longer a waterfall, but a series of iterations that should ideally never do breaking changes, work a lot with feature flags and parallel implementations, and always strive to prevent long-lived feature branches: Modify, Integrate test, rinse & repeat.

2021-10-05 17:20 UTC, Flohack74 commented
I also can add that what @mardy said in https://github.com/ubports/hfd-service/issues/22 is true and I dont like to have to call 5 times into DBus for enabling a darn LED, and yet I still would use the current hfd API for LEDs to reach my goal. I could also say we need to refactor whole hfd and make better APIs inside, and until we reach that goal nobody should use it, but thats the wrong approach. The right approach is: Think about the usability of the product, and see it from the point of a user. Users will not care for the technical solution so much but want a result. So, give them a result, and then lets make it better. And dont make breaking changes that stay around for months and years.

2021-10-05 17:53 UTC, peat-psuwit commented
If I understand it correctly, the issue affects Android 10 ports and Android 9 ports lacking legacy .so-based Light HAL. Have LED ever worked on those? If it has never it's not actually a regression...

> The other PR looks nice, but will it work on old devices?

I believe it should, given that Hfd-service is included in the image.

And, if you prefer to keep the old code, I'm not opposed to that. What I'm asking is a better way to integrate the new code it. Either:
- Write a new class implementing the same interface, and then do the detection and instantiate the correct class [here](https://github.com/ubports/unity8/blob/7b30fe3512d09b4eb0a8cdca5f94bbcab5c7766a/plugins/Lights/plugin.cpp#L28). You don't even have to do the subclass/virtual method; it'll be handled in QObject level. Or:
- Better yet, find out if we can instantiate the Hfd's QML plugin, or somehow make the QML file dynamically use the correct QML plugin. I'm not sure if it'll make the code more ugly or not though...

2021-10-05 18:24 UTC, Flohack74 commented
Well it might have never worked for those devices, but as a user I don't care for the low-level peculiarities: If I am a user changing a device from an old Nexus 5 to a newer device then it will feel like a regression. Technically its not a regression of that kind what you think, but its an incomplete implementation of a feature that drags on, and in my opinion that's even worse: Something was started, but then, for whatever reason, energy was lost to complete it. And that happens mostly when one task is too big to be solved in a reasonable time frame, including testing and documentation, if possible. Its about slicing and scoping out until you get an implementable unit of functionality that can be easily integrated.
Well with my limited time this is off the plate for me. Someone else need to pick that up then. I have a solution that works for me, to get me LED notifications back, and I can install this branch if I update my device.

2021-10-05 18:33 UTC, amartinz commented on plugins/Lights/Lights.cpp
> +    qWarning() << "Testing for availability of hfd interface";
Should this really be a warning or rather be something less verbose?

2021-10-05 18:33 UTC, amartinz commented on plugins/Lights/Lights.cpp
> +    qWarning() << "getprop ro.build.version.sdk result:" << processResult;
Same as above qWarning

2021-10-05 18:33 UTC, amartinz commented on plugins/Lights/Lights.cpp
> +    //else try to initialize a legacy hw module for the LEDs
`// else`

2021-10-05 18:33 UTC, amartinz commented on plugins/Lights/Lights.cpp
> +    //Try first to detect if hfd should be used
`// Try`

2021-10-05 18:39 UTC, amartinz commented
And i agree to Florian's point of view.
We should rather unblock users now and be more agile, especially with all the limited resources we have.

End users care if something works and not how perfectly it is implemented.
From a users point of view all they see "They can not even make a simple light blink, how should i have faith in them being able to manage a whole operating system and trust them with my data when using it as daily driver?"
But that is a whole different discussion and off-topic.

The changes itself look fine and leightweight to me and they are not intrusive.
If there are bigger plans for a certain direction, they can always be pursued but i would prefer to get things in a working state as soon as possible instead of postponing and hoping that we ever get the resources, time and motivation to work on it.

2021-10-06 06:37 UTC, peat-psuwit requested changes
Look, I'm not opposed to unblocking the users. But this is a code review, where we should care about readability and maintainability at least a bit. Otherwise, anyone could commit anything citing "this unblocks user".

Okay, I suppose you're thinking that creating a new class is too much work. That's fine, but at least fix the following, so that it feels less tack-on:

2021-10-06 06:37 UTC, peat-psuwit commented on plugins/Lights/Lights.cpp
> +    int processResult = getpropProcess.readAllStandardOutput().toInt();
We currently has to link against libhybris anyway. Use `property_get()`.

You probably has to link against `libandroid-properties`. See [this file](https://github.com/ubports/unity8/blob/9ec9925db70d3fb34759cf81ce1272e84176a412/src/CMakeLists.txt).

2021-10-06 06:37 UTC, peat-psuwit commented on plugins/Lights/Lights.cpp
> +    }
2 branches of equal importance should take a form of:

```C++
if (m_usesHfd) {
  ...
} else {
  ...
}
```

2021-10-06 06:37 UTC, peat-psuwit commented on plugins/Lights/Lights.cpp
> +    }
Ditto.

2021-10-06 06:37 UTC, peat-psuwit commented on plugins/Lights/Lights.h
> +    bool m_usesHfd;
IIRC, POD type doesn't initialize automatically. Set the default value here, or in initializer list near the constructor, or the constructor itself.

Or, actually, consider eliminating this variable, and initialize `m_hfdInterface` in `init()` instead.

2021-10-06 06:40 UTC, peat-psuwit commented on plugins/Lights/Lights.cpp
> +    int processResult = getpropProcess.readAllStandardOutput().toInt();
Actually, I guess if we try to initialize the legacy HAL first, and then initialize Hfd interface if failed, we might not have to have this property. Unless there exists a device whose legacy HAL is broken...

2021-10-10 19:25 UTC, Flohack74 commented
Alright I went for a subclassed approach as this requires equal work than all the review comments probably ;)

2021-10-12 17:44 UTC, peat-psuwit reviewed
This looks Ok. Most comments are nitpicks. Tested on bq Aquaris 4.5; at least the charging light works, which means at least the legacy code is not broken.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/HfdLights.cpp
> +}
Nitpick: `str*()` functions seems not used (anymore). This should be removable.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/HfdLights.cpp
> +#include <QProcess>
Ditto for `QProcess()`.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/HfdLights.h
> +#define HFD_SERVICE_INTERFACE "com.lomiri.hfd.Leds"
Nitpick: I guess this can be moved to the .cpp file, as they're not used outside the class.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/LegacyLights.cpp
> + * Copyright (C) 2014 Canonical, Ltd.
Nitpick: I believe we're entitled for a copyright too (in addition).

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/HfdLights.h
> +#include <QtGui/QColor>
Nitpick: there's no need to include these in header files.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/LegacyLights.h
> + * Copyright (C) 2014 Canonical, Ltd.
Ditto for copyright.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/LegacyLights.h
> +#include <QtGui/QColor>
Ditto for includes.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/Lights.h
> +#include <QDBusInterface>
Ditto for includes.

2021-10-12 17:44 UTC, peat-psuwit commented on plugins/Lights/plugin.cpp
> +    char buffer[20];
Use `PROP_VALUE_MAX` for the array size. In practice it probably won't exceed, but to be safe.

2021-10-25 16:57 UTC, peat-psuwit approved these changes
So, all comments resolved. Re-tested on bq 4.5 and the charging LED still works. I've tested this on a Volla Phone. I can't see a charging LED. However, I'm not sure if this device has an LED or not; issuing command directly to HFD via `gdbus` doesn't show anything either.

So, if (and only if) you re-tested this on another Android 9 device with an LED, you may merge this.

2021-10-26 15:42 UTC, Flohack74 commented
Yeah, the Vollaphone does not have a LED :) I will re-test since I made substantial changes on my SHIFT 6mq

2021-10-26 15:48 UTC, Flohack74 commented
Aaand it still works. nice. Lets do it!

2021-10-26 15:48 UTC, merged

2021-11-11 17:14 UTC, cibersheep commented
Device: Arale
Channel: RC 2021-W45
Result: Leds seem to work as previously (on notification), tapping on home button when screen is on and when phone is off and charging

2021-11-13 15:36 UTC, Flohack74 commented
We also need a test from a few devices >= Halium9

2021-11-16 12:57 UTC, amartinz commented
I can confirm that it started working for a Halium 10 device with this change, where it did not work previously (axolotl - SHIFT6mq).
But you already know that :smile:

2021-11-18 13:47 UTC, jranaraki commented
LED works on Nexus 6P on RC updated on Nov 17th