Add after update wizard
ubports/unity8 pull request #58
Opened 2018-08-10 12:47 UTC by mariogrip

This adds update wizard that will show after an change to framework has been done. This also adds new pages, one to reinstall/update all apps and one to update/check for firmware update.

REQUIRED PRS:
https://github.com/ubports/system-settings/pull/71
https://github.com/ubports/system-image/pull/5
https://github.com/ubports/ubuntu-touch-meta/pull/23

!don't squash!

2018-08-10 13:21 UTC, NeoTheThird requested changes

2018-08-10 13:21 UTC, NeoTheThird commented on plugins/Wizard/System.cpp
> +if wizard-has-run does exists but does match current framework == show no wizard
"does exist" and "does not exist"

2018-08-10 13:21 UTC, NeoTheThird commented on plugins/Wizard/System.cpp
> +  if (!wizardPathExists())
indentation width should be four spaces for c++

2018-08-10 13:21 UTC, NeoTheThird commented on qml/Wizard/Pages.qml
> +                // impatientLoadingLabel.text = ""
?

2018-08-11 23:13 UTC, mariogrip commented on qml/Wizard/Pages.qml
> +                // impatientLoadingLabel.text = ""
summoning @UniversalSuperBox since he wrote that part ^

2018-08-13 17:04 UTC, mariogrip commented
@NeoTheThird?

2018-08-14 08:04 UTC, NeoTheThird approved these changes

2018-08-14 09:24 UTC, merged