Fixup u8 tests and remove oxide to make arm64 happy
ubports/unity8 pull request #91
Opened 2019-01-07 23:25 UTC by mariogrip

2019-01-07 23:31 UTC, mariogrip commented
*on hold* 
lets wait until we know oxide wont get removed (from edge's rootfs), if so we want to add oxide to armhf meta package.

2019-01-08 02:40 UTC, dobey requested changes

2019-01-08 02:40 UTC, dobey commented on plugins/Wizard/System.cpp
> +          f.open(QFile::WriteOnly);
Please match indentation alignment with the rest of the file for consistency (should be 4 spaces inside if block as seen above this change). :)

2019-02-08 20:44 UTC, UniversalSuperBox approved these changes
I've ensured that this won't remove oxide from the image and updated the indentation. Waiting for @dobey to re-check

2019-02-08 21:32 UTC, dobey approved these changes

2019-02-08 21:34 UTC, merged